export const assigned_appointments = "/appointments/assigned"
export const unassigned_appointments = "/appointments/unassigned"
export const assign_appointment = "/appointments/"
export const authenticate = "/employees/login"
export const create_employees = "/employees"
export const delete_employees = "/employees/"
export const edit_employees = "/employees/"
export const getAll_employees = "/employees"
export const view_employee = "/employee/"

